version: '3.8'
services:
  web:
    image: "mzegarra/websimple:2.0.0"
    build:
      context: .
      dockerfile: ./data/Dockerfile
    volumes:
      - "./data/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 8080:8085